### ISSUE TITLE
The splited context representation

### ISSUE THREAD

**Issue by Punchwes** [ankit-ai/BertQA-Attention-on-Steroids#1]
Hi, Thanks very much for sharing your code for this project, it has been quite helpful.

I have some problem concerning your splitting strategy. The resulting context representation could be regarded as padded from the left(and also right, because the input data has already been padded on the right). Do you think it is plausible to left pad the context? Have you tried to explicitly split the query and context and then right pad them to fixed-length. I find it really hard to explicitly split them for the length of query is not fixed which makes left zeros on the context side hard to handle in a quick fashion.

**Comment by ankit-ai** [comment]
I haven't tried explicit pad alignment because BERT by itself injects positional embeddings (refer paper for details). It would be a good thing to try using the masks which tell you the length of each query and context.

Thanks,
Ankit
